#! /bin/sh

# dependencies: rofi

# main
if [[ "$1" == "--icon" ]]
then
    echo " Launcher"
elif [[ "$1" == "--menu" ]]
then
    rofi -modi drun -show drun -display-drun "Application Launcher"
else
    exit 1
fi
exit 0