#! /bin/sh

# dependencies: rofi nmcli nmtui ttf-material-design-icons(yay)

source "$(dirname "$0")/shared/rofi"

network_icon() {
    active_device_type=$(nmcli device status | grep " connected" | tr -s ' ' | cut -d ' ' -f 2)
    active_connection=$(nmcli device status | grep " connected" | tr -s ' ' | cut -d ' ' -f 4)
    if [[ "$active_device_type" == "wifi"* ]]
    then
        echo " $active_connection" | tr -s ' '
    elif [[ "$active_device_type" == "ethernet"* ]]
    then
        echo " $active_connection" | tr -s ' '
    else
        echo ""
    fi
}

network_menu() {
    menu_items=""
    advanced_item="Advanced Settings"
    menu_items+="$advanced_item\n"
    selected_item=$(rofi_ask "$menu_items" "" "Network Menu")
    if [[ "$selected_item" == "$advanced_item" ]]
    then
        xterm -e "nmtui" &
    else
        exit 1
    fi
}

# main
if [[ "$1" == "--icon" ]]
then
    network_icon
elif [[ "$1" == "--menu" ]]
then
    network_menu
else
    exit 1
fi
exit 0