#! /bin/sh

# dependencies: rofi nmcli nmtui ttf-material-design-icons(yay)

source "$(dirname "$0")/shared/rofi"

get_active_window() {
    xdotool getwindowfocus &>/dev/null
    if [[ "$?" == "0" ]]
    then
        xdotool getwindowfocus
    else
        echo ""
    fi
}

get_window_name() {
    xdotool getwindowclassname $1 | tr [:upper:] [:lower:]
}

activewindow_icon() {
    active_window=$(get_active_window)
    if [[ -z $active_window ]]
    then
        echo ""
    else
        name=$(get_window_name $active_window)
        if [[ -z $name ]]
        then
            echo ""
        else
            echo " $name"
        fi
    fi
}

workspace_icon() {
    focused_desktop=$(bspc query --desktops -d focused)
    for desktop in $(bspc query --desktops)
    do
        if [[ "$desktop" == "$focused_desktop" ]]
        then
            output+=""
        else
            output+=""
        fi
    done
    echo "$output"
}

workspaceswitcher_menu() {
    focused_desktop=$(bspc query --desktops -d focused)
    selected_item=$(rofi_ask "$(bspc query --desktops)" "$focused_desktop" "Workspace Switcher")
    if [[ $selected_item ]]
    then
        bspc desktop -f $selected_item
    else
        exit 1
    fi
}

activewindow_menu() {
    menu_items=""
    active_window=$(get_active_window)
    active_window_name=$(get_window_name $active_window)
    minimize_item="Minimize"
    maximize_item="Maximize"
    close_item="Close"
    kill_item="Kill"
    move_to_right_ws_item="Move to Next Workspace"
    move_to_left_ws_item="Move to Prev Workspace"
    menu_items+="$minimize_item\n"
    menu_items+="$maximize_item\n"
    menu_items+="$close_item\n"
    menu_items+="$kill_item\n"
    menu_items+="$move_to_right_ws_item\n"
    menu_items+="$move_to_left_ws_item\n"
    selected_item=$(rofi_ask "$menu_items" "" "$active_window_name")
    if [[ "$selected_item" == "$minimize_item" ]]
    then
        xdotool windowminimize $active_window
    elif [[ "$selected_item" == "$maximize_item" ]]
    then
        xdotool windowsize $active_window 100% 100%
    elif [[ "$selected_item" == "$close_item" ]]
    then
        xdotool windowclose $active_window
    elif [[ "$selected_item" == "$kill_item" ]]
    then
        xdotool windowkill $active_window
    elif [[ "$selected_item" == "$move_to_right_ws_item" ]]
    then
        new_workspace=$(($(xdotool get_desktop)+1))
        xdotool set_desktop_for_window $active_window $new_workspace
        xdotool set_desktop $new_workspace
    elif [[ "$selected_item" == "$move_to_left_ws_item" ]]
    then
        new_workspace=$(($(xdotool get_desktop)-1))
        xdotool set_desktop_for_window $active_window $new_workspace
        xdotool set_desktop $new_workspace
    else
        exit 1
    fi
}

windowwitcher_menu() {
    switcher_menu_items=""
    selected_window=""
    active_window_pid=$(get_active_window)
    highlighted_item=""
    windows_list=$(xdotool search --name --all --desktop $(xdotool get_desktop) '')
    IFSBAK=$IFS
    IFS=$'\n'
    for window_pid in $windows_list
    do
        item="$window_pid $(get_window_name $window_pid)"
        switcher_menu_items+="$item\n"
        if [[ "$window_pid" == "$active_window_pid" ]]
        then
            highlighted_item="$item"
        fi
    done
    IFS=$IFSBAK

    selected_item=$(rofi_ask "$switcher_menu_items" "$highlighted_item" "Window Switcher")
    if [[ -z $selected_item ]]
    then
        exit 1
    else
        selected_item_pid=$(echo $selected_item | cut -d ' ' -f 1)
        xdotool windowactivate $selected_item_pid
    fi
}

next_workspace() {
    active_workspace=$(xdotool get_desktop)
    workspaces_length=$(xdotool get_num_desktops)
    new_workspace=$((active_workspace+1))
    if [[ "$new_workspace" -lt "$workspaces_length" ]]
    then
        xdotool set_desktop $new_workspace
    else
        exit 1
    fi
}

prev_workspace() {
    active_workspace=$(xdotool get_desktop)
    new_workspace=$((active_workspace-1))
    if [[ "$new_workspace" -gt "-1" ]]
    then
        xdotool set_desktop $new_workspace
    else
        exit 1
    fi
}

list_of_windows_in_current_workspace() {
    xdotool search --name --desktop $(xdotool get_desktop) ''
}

next_window() {
    active_window_pid=$(get_active_window)
    windows_list=$(list_of_windows_in_current_workspace)
}

prev_window() {
    active_window_pid=$(get_active_window)
    windows_list=$(list_of_windows_in_current_workspace)
}

# main
if [[ "$1" == "--active-window-icon" ]]
then
    activewindow_icon
elif [[ "$1" == "--workspace-icon" ]]
then
    workspace_icon
elif [[ "$1" == "--workspace-switcher-menu" ]]
then
    workspaceswitcher_menu
elif [[ "$1" == "--next-workspace" ]]
then
    next_workspace
elif [[ "$1" == "--prev-workspace" ]]
then
    prev_workspace
elif [[ "$1" == "--active-window-menu" ]]
then
    activewindow_menu
elif [[ "$1" == "--window-switcher-menu" ]]
then
    windowwitcher_menu
elif [[ "$1" == "--next-window" ]]
then
    next_window
elif [[ "$1" == "--prev-window" ]]
then
    prev_window

else
    exit 1
fi
exit 0