#! /bin/sh

bspc monitor -d I II III IV

sxhkd &

bspc config border_width 1
bspc config window_gap 8
bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config top_padding 36
bspc config normal_border_color "#000000"
bspc config active_border_color "#000000"
bspc config focused_border_color "#dd30ff"
bspc config border_radius 8

polybar main &