#! /bin/sh
primary_monitor="$1"

bspc query -M --names | grep -v "$primary_monitor" | xargs -I {} bspc monitor {} --remove

off_commands=$(xrandr | awk '$2 == "connected"{print $1}' | grep -v "$primary_monitor" | xargs -I {} echo -n "--output {} --off ")

command="xrandr --output $primary_monitor --primary --auto $off_commands"
$command
